#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'lane-detection-py','console_scripts','lane_detection_node'
__requires__ = 'lane-detection-py'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('lane-detection-py', 'console_scripts', 'lane_detection_node')()
    )
