#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'line-following-bot','console_scripts','lane_detection_node'
__requires__ = 'line-following-bot'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('line-following-bot', 'console_scripts', 'lane_detection_node')()
    )
